### ISSUE TITLE
Firebase auth

### ISSUE THREAD

**Issue by EzraKim09** [EzraKim09/QRAttendance#4]
Create a Firebase auth system for the instructor and admin login

**Comment by grantgarbe** [comment]
If you want to create a Firebase auth system, you need to make sure you have an account with Firebase and make sure you enable Auth. Once you did that, you can choose which type of login you want to use (Google, Facebook, GitHub, etc.). What type of service provider are you going to use? This information can help me figure out what other information to give you.

**Comment by EzraKim09** [comment]
Done, much easier than expected as I had already done a similar thing before. The main problem was that since the user had already login using their google acc before this, I had to make some changes.

Also, instead of email and password, I made some changes so it will feel like username and password to the user.
